# Generated by Django 5.0.6 on 2024-05-29 16:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Impuestos',
            fields=[
                ('idImpuesto', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Impuesto')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('fechaInicial', models.DateField(verbose_name='Fecha Inicial')),
                ('fechaFinal', models.DateField(verbose_name='Fecha Final')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Impuesto',
                'verbose_name_plural': 'Impuestos',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Producto')),
                ('nombreProducto', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^(?!.*(\\w)\\1{2,}).+$', 'No se pueden ingresar letras repetidas más de 2 veces')], verbose_name='Nombre de Producto')),
                ('descripcion', models.CharField(max_length=2000, validators=[django.core.validators.RegexValidator('^(?!.*(\\w)\\1{2,}).+$', 'No se pueden ingresar letras repetidas más de 2 veces')], verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Descuento')),
                ('stockMinimo', models.IntegerField(verbose_name='Stock Mínimo')),
                ('stockMaximo', models.IntegerField(verbose_name='Stock Máximo')),
                ('imagenProducto', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen de Producto')),
                ('idImpuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.impuestos', verbose_name='Impuesto')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
