# Generated by Django 4.0.5 on 2024-06-18 18:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Impuesto')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre')),
                ('estado', models.CharField(default='', max_length=50)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.AddField(
            model_name='impuestos',
            name='estado',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='productos',
            name='estado',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='productos',
            name='informacionAdicional',
            field=models.CharField(default=1, max_length=2000, validators=[django.core.validators.RegexValidator('^(?!.*(\\w)\\1{2,}).+$', 'No se pueden ingresar letras repetidas más de 2 veces')], verbose_name='Informacion Adicional'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productos',
            name='usuario_creacion',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='productos',
            name='idCategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.categoria', verbose_name='Categoria'),
        ),
    ]
