# Generated by Django 4.0.5 on 2024-06-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_productoimagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagenCategoria',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen de Categoria'),
        ),
        migrations.AddField(
            model_name='productos',
            name='contacto',
            field=models.CharField(default=1, max_length=10, verbose_name='Número telefónico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productos',
            name='fecha_creacion',
            field=models.DateTimeField( max_length=200, verbose_name='Fecha de Creacion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productoimagen',
            name='imagen',
            field=models.ImageField(upload_to='', verbose_name='Imagen del Producto'),
        ),
    ]
