# Generated by Django 4.0.5 on 2024-06-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_categoria_imagencategoria_productos_contacto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, editable=False, max_length=200, null=True, verbose_name='Fecha de Creacion'),
        ),
    ]
