# Generated by Django 4.0.5 on 2024-06-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_alter_productos_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='idImpuesto',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='stockMaximo',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='stockMinimo',
        ),
        migrations.AddField(
            model_name='productos',
            name='facebook',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número telefónico'),
        ),
        migrations.DeleteModel(
            name='Impuestos',
        ),
    ]
