# Generated by Django 4.0.5 on 2024-06-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_remove_productos_idimpuesto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='facebook',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Facebook'),
        ),
    ]
